window.projects = [
  {
    title: 'automateFitness',
    description: 'Using proprietary machine learning algorithms, this app tracks your fitness and understands which exercises are being performed without manual intervention.',
    tags: 'app, mobile, website, design, branding',
    link: 'https://dribbble.com/shots/5253468',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/5253468/automatefitness-full.jpg',
    more: '',
  },
  {
    title: 'Pittsburgh Cares',
    description: 'Steel City Codefest 2014 Finalist Team "Think Outside the Sandbox" for Pittsburgh Cares.',
    tags: 'app, mobile, design',
    link: 'https://dribbble.com/shots/5260423',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/5260423/pghcares.jpg',
    more: '',
  },
  {
    title: 'Datumbased',
    description: 'This Data-Pipeline-As-A-Service allows users to iterate on their core value-add in minimal time without the costs of hiring and managing an entire technology team.',
    tags: 'app, website, design, branding',
    link: 'https://dribbble.com/shots/6199222',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/6199222/screen_shot_2019-03-18_at_16.59.30-fullpage_4x.png',
    more: 'https://datumbased.com',
  },
  {
    title: '3D Network Visualization',
    description: 'An interactive, 3D network data visualization displaying entity connections using D3 and Three.js.',
    tags: 'data visualization',
    link: 'https://dribbble.com/shots/6198114',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/6198114/3d.gif',
    more: '',
  },
  {
    title: 'Clustering Visualization',
    description: 'An interactive 3D TSNE clustering visualization of word embeddings generated using natural language processing (NLP) techniques and tensorflow embedding projector.',
    tags: 'data visualization, machine learning, data science',
    link: 'https://dribbble.com/shots/10983481',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/10983481/media/57350418b825b658689643648698db00.gif',
    more: '',
  },
  {
    title: 'SimpleStore',
    description: 'SimpleStore is a clean, responsive storefront boilerplate with no database you can setup in minutes.',
    tags: 'app, website, open source',
    link: 'https://dribbble.com/shots/5263598',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/5263598/simplestore-full.jpg',
    more: 'https://chrisdiana.dev/simplestore/',
  },
  {
    title: 'Big Data A.I.',
    description: 'A big data, machine learning and artificial intelligence consulting company focused on delivering high quality projects and products.',
    tags: 'website, branding, logo',
    link: 'https://dribbble.com/shots/11012098',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/11012098/media/2e200f016cb2ac35346a126177dd8766.jpg',
    more: '',
  },
  {
    title: 'RamenBar',
    description: 'The finest ramen restaurant in Pittsburgh, RamenBar serves the area top-notch cuisine and take-out.',
    tags: 'website, branding, logo',
    link: 'https://dribbble.com/shots/4670169',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/4670169/ramenbar.jpg',
    more: 'http://ramenbarpittsburgh.com',
  },
  {
    title: 'TruckDuty',
    description: 'A career site and job board geared towards the logistics and transporation industry.',
    tags: 'app, mobile, website, branding, logo',
    link: 'https://dribbble.com/shots/5263724',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/5263724/truckduty-full.jpg',
    more: '',
  },
  {
    title: 'Loclii',
    description: 'A location based suggestion application that allows users to find interesting things near them.',
    tags: 'app, mobile, website, branding',
    link: 'https://dribbble.com/shots/4610070',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/4610070/loclii-full.jpg',
    more: '',
  },
  {
    title: 'Comeback Clothing',
    description: 'An alternative sports apparel company focused on sponsoring athletes in action sports.',
    tags: 'website',
    link: 'https://dribbble.com/shots/4670175',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/4670175/comebackclothing.jpg',
    more: 'http://comeback-clothing.com/shop/',
  },
  {
    title: 'Network Data Visualization',
    description: 'A 2D data visualization and manipulation of a network with nodes and edges built with D3.',
    tags: 'data visualization',
    link: 'https://dribbble.com/shots/6198120',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/6198120/vis.gif',
    more: '',
  },
  {
    title: 'CMS.js',
    description: 'CMS.js is a fully Client-side, JavaScript Markdown Site generator in the spirit of Jekyll that uses plain ol\' HTML, CSS and JavaScript to generate your website. CMS.js is like a file-based CMS. It takes your content, renders Markdown and delivers a complete website in Single-Page App fashion...without the aid of server-side scripting (no Node.js, PHP, Ruby, etc.).',
    tags: 'open source',
    link: 'https://dribbble.com/shots/5263715',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/5263715/cms-js-full.jpg',
    more: 'http://chrisdiana.github.io/cms.js',
  },
  {
    title: 'Crimper\'s Climbing',
    description: 'The best climbing gym in the great state of West Virginia, Crimper\'s Climbing Gym gives locals a place to fix their climbing itch.',
    tags: 'website',
    link: 'https://dribbble.com/shots/6192817',
    src: 'https://cdn.dribbble.com/users/84464/screenshots/6192817/crimpers-full.jpg',
    more: '',
  },
];
